"""Core coverage checking logic for CODEOWNERS."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Dict, List, Set

import pathspec

from .config import Config
from .matcher import CodeOwnersPatternMatcher


class CoverageChecker:
    """Check CODEOWNERS coverage for repository files."""

    def __init__(self, config: Config) -> None:
        """
        Initialize coverage checker.

        Args:
            config: Configuration object
        """
        self.config = config
        self.matcher = CodeOwnersPatternMatcher(config.codeowners_path)
        self.exclusions = pathspec.PathSpec.from_lines("gitignore", config.exclusions)

    def get_repository_files(self) -> List[str]:
        """
        Get all files in repository using git ls-files.

        Returns:
            List of file paths relative to repository root
        """
        result = subprocess.run(
            ["git", "ls-files"],
            capture_output=True,
            text=True,
            check=True,
        )
        files = result.stdout.strip().split("\n")
        # Filter out empty strings
        return [f for f in files if f]

    def _load_baseline(self) -> Set[str]:
        """
        Load baseline file of allowed uncovered files.

        Returns:
            Set of file paths that are allowed to be uncovered
        """
        baseline_path = Path(self.config.baseline_path)

        if not baseline_path.exists():
            return set()

        baseline_files = set()
        with open(baseline_path) as f:
            for line in f:
                line = line.strip()
                # Skip comments and empty lines
                if line and not line.startswith("#"):
                    baseline_files.add(line)

        return baseline_files

    def check_coverage(self, files: List[str] | None = None) -> Dict[str, object]:
        """
        Check which files lack CODEOWNERS coverage.

        Args:
            files: Optional list of specific files to check.
                   If None, checks all repository files.

        Returns:
            Dictionary with coverage statistics:
            {
                "total_files": int,
                "covered_files": int,
                "uncovered_files": [list of uncovered file paths],
                "baseline_files": [list of baseline file paths],
                "coverage_percentage": float
            }
        """
        if files is None:
            files = self.get_repository_files()

        # Filter excluded files
        filtered_files = [f for f in files if not self.exclusions.match_file(f)]

        # Check coverage
        uncovered = [f for f in filtered_files if not self.matcher.matches(f)]

        # Load baseline
        baseline = self._load_baseline()

        # Separate new uncovered files from baseline files
        new_uncovered = [f for f in uncovered if f not in baseline]
        baseline_files = [f for f in uncovered if f in baseline]

        # Calculate coverage
        total_files = len(filtered_files)
        covered_files = total_files - len(uncovered)
        coverage_percentage = (covered_files / total_files * 100) if total_files > 0 else 100.0

        return {
            "total_files": total_files,
            "covered_files": covered_files,
            "uncovered_files": new_uncovered,
            "baseline_files": baseline_files,
            "coverage_percentage": coverage_percentage,
        }

    def generate_baseline(self, files: List[str] | None = None) -> List[str]:
        """
        Generate a baseline of all currently uncovered files.

        Args:
            files: Optional list of specific files to check.
                   If None, checks all repository files.

        Returns:
            List of uncovered file paths (sorted)
        """
        if files is None:
            files = self.get_repository_files()

        # Filter excluded files
        filtered_files = [f for f in files if not self.exclusions.match_file(f)]

        # Check coverage
        uncovered = [f for f in filtered_files if not self.matcher.matches(f)]

        return sorted(uncovered)

    def write_baseline(self, baseline_files: List[str]) -> None:
        """
        Write baseline file.

        Args:
            baseline_files: List of file paths to write to baseline
        """
        baseline_path = Path(self.config.baseline_path)
        baseline_path.parent.mkdir(parents=True, exist_ok=True)

        with open(baseline_path, "w") as f:
            f.write("# CODEOWNERS Coverage Baseline\n")
            f.write("# Files lacking CODEOWNERS coverage (sorted)\n")
            f.write("# Goal: Reduce this list to zero\n")
            f.write("#\n")
            f.write("# Generated by: codeowners-coverage baseline\n")
            f.write("#\n")
            f.write("\n")

            for filepath in baseline_files:
                f.write(f"{filepath}\n")
